### PR TITLE
Fix assertion when no gsettings schema installed

### PR DESCRIPTION
**Pull request by TingPing**

### CODE REVIEW

**Comment by mwleeds** [comment]
Looking at the docs for `g_once_init_enter`, shouldn't `gtk_theme` be set to 0 when it's declared? I know that's not changed by this patch, just something I noticed.

**Comment by TingPing** [comment]
It is a static variable so it defaults to 0.

**Comment by mwleeds** [comment]
LGTM

**Comment by mwleeds** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
