### PR TITLE
update russian translation

### PR DESCRIPTION
**Pull request by kloun**

### CODE REVIEW

**Comment by kloun** [comment]
bot, add author to whitelist

**Comment by kloun** [comment]
bot, test pull request

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r+

**Comment by kloun** [comment]
why tests don't work?

**Comment by kloun** [comment]
@matthiasclasen hello. I fixed build. ok?

**Comment by matthiasclasen** [comment]
bot, retest please

**Comment by matthiasclasen** [comment]
bot, retest please

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
