### PR TITLE
extra_data: In system-helper case, canonicalize uid/gid

### PR DESCRIPTION
**Pull request by alexlarsson**
Make sure all files produced by apply_extra are owned by root.

### CODE REVIEW

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r+

**Comment by TingPing** [comment]
Shouldn't you ensure `--user` is owned by the current user also?

**Comment by Erick555** [comment]
@TingPing Is it possible that it isn't? I think unprivileged user can't create files owned by someone else.

**Comment by TingPing** [comment]
@Erick555 	I think I've seen extracting an archive creating files owned by different uid. Maybe I'm wrong though.

**Comment by alexlarsson** [comment]
@TingPing a non-root user can't chown a file to someone else. Not sure about groups though. Can a user change the group of a file to a non-primary group the user is part of?

**Comment by Erick555** [comment]
> Can a user change the group of a file to a non-primary group the user is part of?

@alexlarsson I tested it and that's possible.

**Comment by alexlarsson** [comment]
Is that a problem though? Its still owned by the user...

**Comment by TingPing** [comment]
Its probably not harmful but it probably also isn't done on purpose.

**Pull request closed without merging**
