### PR TITLE
Update hi.po

### PR DESCRIPTION
**Pull request by gostsdmitry**
Minor fixes

### CODE REVIEW

**Comment by gostsdmitry** [comment]
@mwleeds Sorry. What does this mean: Error: The operation was canceled.

Annotations
2 errors
Run tests in valgrind
The run was canceled.
Run tests in valgrind
The operation was canceled. ?

**Comment by gostsdmitry** [comment]
Are these errors not critical?

**Comment by mwleeds** [comment]
@gostsdmitry I cancelled one of the CI jobs (the valgrind one) since it is pointless to run for a patch like this

**Comment by gostsdmitry** [comment]
It's clear. Thanks!

**Pull request merged**
