### PR TITLE
Implicity grant MPRIS2 permissions

### PR DESCRIPTION
**Pull request by TingPing**
This should be safe to expose without requiring everybody request it and users accept it.

### CODE REVIEW

**Comment by TingPing** [comment]
No, this is only about ownership of your own MPRIS service.

**Comment by alexlarsson** [comment]
Do people actually use the full app id as an MPRIS id?

**Comment by alexlarsson** [comment]
Also, to be backwards compat with older flatpaks you'd have to specify this anyway.

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
