### PR TITLE
Add tests for private apis

### PR DESCRIPTION
**Pull request by matthiasclasen**
Rearrange the build with convenience libraries, and add a test that links against those, so we can test some of the private apis that we rely on.

### CODE REVIEW

**Comment by alexlarsson** [comment]
Looks good, but needs rebase.

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r=alexlarsson

**Comment by alexlarsson** [comment]
wth? that was the largest warning i've ever seen???

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
