### PR TITLE
Store more flatpakrepo fields

### PR DESCRIPTION
**Pull request by matthiasclasen**
Store comment, description, homepage, and icon and make these fields available for libflatpak users.

This will be used by gnome-software to present remotes to users.

### CODE REVIEW

**Comment by matthiasclasen** [comment]
Closes: https://github.com/flatpak/flatpak/issues/2810

**Comment by alexlarsson** [comment]
Its a bit weird that we only have a remote list command and not one that gives info about a particular remote. But this looks good.

xa.title can also be stored in the repo metadata (see e.g. flatpak build-update-repo 
--title=TITLE) allowing upstream to later change and propagate the new info to the client. This comes with a separate xa.title-is-set key to track if the value is locally set. Maybe we should do the same for the new fields.

**Comment by matthiasclasen** [comment]
I'll look at those is-set fields

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
