### PR TITLE
allow remote add to succeed when offline

### PR DESCRIPTION
**Pull request by ramcq**
Updating the metadata at the end of adding a remote means that it fails
if we're offline, even if we have the .flatpakrepo file available.
Unlike the other error cases in the process, which mean the operation
really has messed up, the remote is actually usable even if the
metadata update fails, because future operations will grab the
summary and any new metadata - so we should change this to a warning
to allow the operation to succeed when we're offline.

https://github.com/flatpak/flatpak/issues/917

### CODE REVIEW

**Comment by matthiasclasen** [comment]
The general idea sounds good to me.

The one thing I'm a bit unsure about here is matching on G_IO_ERROR_FAILED. That error code is widely used as the universal 'something failed, but I'm too lazy to set up a GError enum' fallback value.

**Comment by ramcq** [comment]
@matthiasclasen I had a poke around in the pull and fetch code in ostree, and indeed they are too lazy to set up GError enum. My reading was, if it's not an explicit error like the proxy screwing up, or 404 not found, which seem legitimately broken and worth propagating the error up, all of the other network fetch errors seemed to map to G_IO_ERROR_FAILED.

**Comment by pwithnall** [comment]
If it would help, we could use some more specific error mappings in libostree here.

**Comment by matthiasclasen** [comment]
I'll merge this anyway. If we find error conditions that should cause it to fail bug give us a warning now, we can plead for error codes from libostree.

**Comment by cgwalters** [comment]
I think we can/should integrate with `GNetworkMonitor` to detect offline state better; we could fairly easily add an API to libostree like `ostree_repo_can_pull()` or something.

**Comment by cgwalters** [comment]
As far as error codes...the thing is the API/ABI surface they expose is huge and full of tricky semantic details.  My preference is generally to add explicit API for the common things like "open_file_allow_noent" rather than "open file, catch G_IO_ERROR_NOT_FOUND".  Among other things it avoids doing a malloc for the `GError`.

We *do* in libostree map all of the POSIX error codes via gio.  HTTP is harder particularly because we have both libcurl/libsoup backends, and so we can't just re-export e.g. soup GErrors.

**Comment by ramcq** [comment]
Well, excitingly that this doesn't actually work because the error actually comes first from G_RESOLVER_ERROR in the entirely offline case. So I need to add that case... :)

Given the effort we're making into pulling from USBs, DVDs, LANs etc - API that assumes global network connectivity equates to successful pulling is probably an oversimplification - but maybe at the end of all of that yak-shaving there will be a function like "do you have any sources for this" and the answer might be no.

I did think about adding some "OK if this fails" to the API but it seemed like it would go way too far into the guts of everything - basically any potential error path which can bork on network - to be worthwhile vs just catching the exception at the top knowing that, in this invocation, failure is not all that bad. We'd do this in the shell script with like || true, but we want other flatpak/disk/repo/etc housekeeping failures to fail properly, because later in the script we make changes to the deployed apps which would go badly wrong if the remote wasn't added.

**Pull request merged**
