### PR TITLE
Update Czech translation

### PR DESCRIPTION
**Pull request by AsciiWolf**
Fix small typo.

### CODE REVIEW

**Comment by mwleeds** [comment]
@rh-atomic-bot r+

**Comment by AsciiWolf** [comment]
It looks like CI got stuck on something.

**Comment by mwleeds** [comment]
bot, retest please

**Comment by AsciiWolf** [comment]
Still nothing. :-(

**Comment by AsciiWolf** [comment]
@mwleeds @alexlarsson Any chance that this will be merged or should I create a new PR?

**Comment by mwleeds** [comment]
bot, test pull request

**Comment by mwleeds** [comment]
bot, retest this please

**Pull request merged**
