### PR TITLE
Various 1.8 backports from master

### PR DESCRIPTION
**Pull request by alexlarsson**

### CODE REVIEW

**Comment by mwleeds** [comment]
Maybe we want to backport `c6647c2b transaction: Fix ordering of runtime uninstallation`

**Comment by alexlarsson** [comment]
> `c6647c2b`

Yeah, that makes sense

**Comment by mwleeds** [comment]
And maybe ff2e7d6e

**Comment by alexlarsson** [comment]
> And maybe [ff2e7d6](https://github.com/flatpak/flatpak/commit/ff2e7d6e90166241126e28434b2fc3e9afaf821d)

That one conflicts with the branch, so needs manual work. Might still make sense to do.

**Comment by mwleeds** [comment]
Downstream we backported some summary caching fixes: https://github.com/endlessm/flatpak/pull/242

**Comment by mwleeds** [comment]
And we probably want e39b94b2

**Comment by mwleeds** [comment]
I think that's all though.

**Pull request merged**
