### PR TITLE
Add semantic support for network installations

### PR DESCRIPTION
**Pull request by ananace**
Just to add a bit of validity to the thought of running a NFS-backed - write one, read many - client application installation for Linköpings University.

### CODE REVIEW

**Comment by alexlarsson** [comment]
bot, add author to whitelist

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Comment by alexlarsson** [comment]
Did you try it over NFS yet?

**Comment by ananace** [comment]
Still in Brussels for CfgMgmtCamp, so haven't had time to do anything about actually deploying the system.

Will report back on how it actually works though once tested.

**Pull request closed without merging**
