### PR TITLE
dir: Use new AccountsService feature to get languages

### PR DESCRIPTION
**Pull request by hadess**
Use the new GetUsersLanguages() method from AccountsService to get the
list of all the locales that each user is interested in.

See https://gitlab.freedesktop.org/accountsservice/accountsservice/-/merge_requests/99

Closes: #5006

### CODE REVIEW

**Comment by hadess** [comment]
This is only compile tested, but I think that I took care to make sure that the old code paths were still used if the `GetUsersLanguages()` method (for system repos), or the `Languages` property (for user repos) were missing.

**Comment by hadess** [comment]
I couldn't figure out how to run the test suite locally, running `make check` in the builddir fails with a single line error, and running `.libs/testlibrary` fails copying some gpg files when I try to list the tests it includes.

**Comment by hadess** [comment]
> I couldn't figure out how to run the test suite locally, running `make check` in the builddir fails with a single line error, and running `.libs/testlibrary` fails copying some gpg files when I try to list the tests it includes.

Found the bug: https://github.com/flatpak/flatpak/issues/5020

**Comment by hadess** [comment]
With the additional change, the tests pass (although it would probably be better to force that locale inside the test itself), but new errors showed up. Given that I couldn't figure out how to run individual tests, I'm going to leave it at that.

**Comment by hadess** [comment]
> @hadess would you mind if I take it over, and push to your branch? Would you prefer me to open a new pull request with the rebased and updated patches? Or, would you prefer actual code review and you'll update the patchset?

You can take over, I probably won't have time to look into problems with the code or write tests any time soon. And feel free to change the author to yourself if you need to do anything but the most minuscule of changes.

Still super interested in seeing this land!

**Comment by GeorgesStavracas** [comment]
This should be ready now. I changed two things in the second patch:

 * The `(^o)` GVariant format was wrong for `g_variant_get`, just using `(o)` is fine
 * Merge `locale_langs` in addition to `get_user_locales()`, instead of either/or

**Review by TingPing — APPROVED** [review]

**Comment by GeorgesStavracas** [comment]
I did not notice the approval, let's go with this :)

**Pull request merged**
