### PR TITLE
Add new API to the docs

### PR DESCRIPTION
**Pull request by mariospr**
Some of this API has been added a while ago, but never
made it to the sections file, so add it now.

PS: This also can be applied to the 0.8.x branch.

### CODE REVIEW

**Comment by mariospr** [comment]
The test suite failure seems unrelated:
```
++ ostree trivial-httpd --autoexit --daemonize -p httpd-port repos
error: No such file or directory
+ cleanup
+ /bin/kill 10346
+ gpg-connect-agent --homedir /var/tmp/test-flatpak-AOKPT1/gpghome killagent /bye
Updating summary
+ fusermount -u /var/tmp/test-flatpak-AOKPT1/runtime/doc
fusermount: failed to unmount /var/tmp/test-flatpak-AOKPT1/runtime/doc: No such file or directory
+ :
+ rm -rf /var/tmp/test-flatpak-AOKPT1
```

**Comment by alexlarsson** [comment]
@rh-atomic-bot retest

**Comment by alexlarsson** [comment]
@rh-atomic-bot test

**Comment by alexlarsson** [comment]
bot, retest this please

**Comment by alexlarsson** [comment]
bot, retest this please

**Comment by alexlarsson** [comment]
bot, retest this please

**Comment by alexlarsson** [comment]
bot, retest this please

**Pull request merged**
