### PR TITLE
run: propagate wildcard xauth entries to app bundle

### PR DESCRIPTION
**Pull request by halfline**
At the moment, flatpak applications are only given FamilyLocal family
xauth cookies from the Xauthority file.  This is so, the sandboxed
application doesn't inadvertently get access to displays on other
computers.

But FamilyLocal isn't the only xauth family that's local.  FamilyWild
entries can be local as well.

Furthermore, FamilyWild entries are preferable to FamilyLocal entries
when found, because they don't break if the system hostname is changed.

This commit makes FamilyWild xauth entries get propagated in the same
way as their FamilyLocal counterparts.

### CODE REVIEW

**Comment by halfline** [comment]
(note this patch isn't yet tested) Kekun is going to test it and give feedback here.

**Comment by Kekun** [comment]
I finally tested it, but it didn't solve the problem even after a reboot "just in case".

**Comment by halfline** [comment]
Thanks for testing.  I should be on irc tomorrow if youre around.  I'll need to look at your new xauth file.

**Comment by Kekun** [comment]
I won't be available all the time tomorrow unfortunately, but sure we can try.

**Comment by Kekun** [comment]
I applied the patch wrongly, once properly tested your patch works! :)

**Pull request merged**
