### PR TITLE
dir: Also add runtimes to flatpak_dir_find_remote_related

### PR DESCRIPTION
**Pull request by smspillaz**
The runtime is also an interesting ref to install too

### CODE REVIEW

**Comment by alexlarsson** [comment]
No, the runtime is a direct dependency, not a related ref, you need to handle those differently.

**Comment by smspillaz** [comment]
@alexlarsson how would you suggest handling it then? In the caller itself? Or should libflatpak provide a mechanism to handle this? As far as I can tell there is nothing in the libflatpak API that tells you the runtime for a ref, nor does `flatpak_installation_install*` install it for you

**Comment by alexlarsson** [comment]
@smspillaz The current API for this is flatpak_installation_fetch_remote_metadata_sync, as used in gnome-software in e.g. gs_flatpak_create_runtime_from_metadata().

However, the long term goal is to export some form of the higher level transaction code that flatpak-update uses: https://github.com/flatpak/flatpak/issues/1234
That needs close syncing with what gnome-software wants/needs though.

**Comment by smspillaz** [comment]
> The current API for this is flatpak_installation_fetch_remote_metadata_sync, as used in gnome-software in e.g. gs_flatpak_create_runtime_from_metadata().

Hrm, okay. Not super ideal, but I suppose as long as we can make that work offline with the work being done in https://github.com/flatpak/flatpak/pull/1575 then this isn't so bad.

**Pull request closed without merging**
