### PR TITLE
Add Hindi translation

### PR DESCRIPTION
**Pull request by gostsdmitry**
Added translation of the interface into Hindi.

### CODE REVIEW

**Comment by gasinvein** [comment]
This largely reverts latest russian translation from #4298 to the previous state. Is it intentional or some failed merge?

**Review by gasinvein — DISMISSED** [review]
I strongly suggest splitting Hindi and Russian translations to separate pull requests. The later probably needs to be redone on top of current master branch.

**Comment by smcv** [comment]
> I strongly suggest splitting Hindi and Russian translations to separate pull requests

Yes, one merge request per translation, please. #4342 is a good example; I don't speak Russian, so I can't comment on the accuracy of the translation, but the mechanics of the pull request seem correct.

**Comment by gostsdmitry** [comment]
> Это в значительной степени возвращает русский перевод из последнего (как после #4298) в предыдущее состояние. Это намеренное или какое-то неудачное слияние?

No. Not intentionally.

**Comment by gostsdmitry** [comment]
> I strongly suggest splitting Hindi and Russian translations to separate pull requests. The later probably needs to be redone on top of current master branch.

OK.

**Comment by gasinvein** [comment]
`git diff flatpak-1.10.x..be9d560 -- po/ru.po` suggests that this translation is based on some ≤1.10 version.

**Comment by gostsdmitry** [comment]
> I strongly suggest splitting Hindi and Russian translations to separate pull requests. The later probably needs to be redone on top of current master branch.

I deleted the Russian translation file and left a file with a Hindi translation in the request.

**Comment by gasinvein** [comment]
Committing the file deletion means that merging this PR will delete the original file from the repository.

**Comment by gostsdmitry** [comment]
> Committing the file deletion means that merging this PR will delete the original file from the repository.

Yes. But I got everything back by copying the Russian translation to my repository.

**Comment by gostsdmitry** [comment]
For the subsequent possible correction of the translation, I have created a separate repository.

**Comment by gostsdmitry** [comment]
> Broken translation was removed.
Sorry. What translation do you call broken? The one that I was correcting now?

**Comment by gasinvein** [comment]
This was a comment to why I'm dismissing my "changes requested" review. Russian translation was based on an outdated version, but since it's now removed, I don't request any more changes.

**Comment by gostsdmitry** [comment]
> This was a comment to why I'm dismissing my "changes requested" review. Russian translation was based on an outdated version, but since it's now removed, I don't request any more changes.

Ok. If I understand correctly, there are still people who speak Russian among the translators. As for Hindi, I have now completed the translation into that language. I created a separate repository in which I copied the Hindi translation. If necessary, I will edit it there.

**Comment by gostsdmitry** [comment]
Hindi translation completed.

**Comment by AsciiWolf** [comment]
@gostsdmitry You also need to add "hi" to the [LINGUAS](https://github.com/flatpak/flatpak/blob/master/po/LINGUAS) file.

**Comment by AsciiWolf** [comment]
I see just one file change in your current PR. Maybe you accidentally reverted it?

**Comment by gostsdmitry** [comment]
> I see just one file change in your current PR. Maybe you accidentally reverted it?



> I see just one file change in your current PR. Maybe you accidentally reverted it?

I added the language code to my repository later than I submitted a pull request.

**Comment by gostsdmitry** [comment]
> I see just one file change in your current PR. Maybe you accidentally reverted it?

Take a look #4401
Have I done everything right?

**Comment by AsciiWolf** [comment]
The LINGUAS update is already a part of this PR (you pushed it to the same branch), no need to create a separate PR for this.

**Comment by gostsdmitry** [comment]
> The LINGUAS update is already a part of this PR (you pushed it to the same branch), no need to create a separate PR for this.

That is, I can edit the LINGUAS file in the Flatpak repository?

**Comment by gostsdmitry** [comment]
What should I specify in line 13 "Language-Team:" if I am not a member of any translation team?
Please tell me.

**Comment by AsciiWolf** [comment]
> @AsciiWolf What should I specify in line 13 "Language-Team:" if I am not a member of any translation team?
> Please tell me.

Hmm, good question. I see that other GNOME projects have `"Language-Team: Hindi <kde-i18n-doc@kde.org>\n"` in their Hindi translations, so I would probably use this. The GNOME own Hindi translation team does not seem to be active.

**Comment by AsciiWolf** [comment]
> I added the Hindi language code to my repository in the LINGUAS file. It's enough?

Yeah, it looks good now.

**Comment by AsciiWolf** [comment]
By the way, feel free to also translate [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) and [xdg-desktop-portal-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk) into Hindi. :-)

**Comment by gostsdmitry** [comment]
I did something else.
https://github.com/gostsdmitry/flatpak-docs/tree/master/po/ru/LC_MESSAGES
:-)

**Comment by gostsdmitry** [comment]
The fact is that I prefer to translate offline. I download the program, translate the localization file using poedit, and after that I upload it to my forks.

**Comment by gostsdmitry** [comment]
> By the way, feel free to also translate [xdg-desktop-portal](https://github.com/flatpak/xdg-desktop-portal) and [xdg-desktop-portal-gtk](https://github.com/flatpak/xdg-desktop-portal-gtk) into Hindi. :-)
Thanks! If I have free time, I will translate it. :-)

**Comment by gostsdmitry** [comment]
@AsciiWolf I have translated xdg-desktop-portal to Hindi, but I am having problems splitting pull requests as I have frozen the Traditional Chinese translation...

**Comment by AsciiWolf** [comment]
> @AsciiWolf I have translated xdg-desktop-portal to Hindi, but I am having trouble splitting pull requests since I completed the Traditional Chinese translation...

You have to create a separate [Git Branch](https://www.atlassian.com/git/tutorials/using-branches) for every PR in your forked repository. Learn how to work with the `git branch` command and Git branches on GitHub.

**Comment by gostsdmitry** [comment]
@AsciiWolf 
https://github.com/flatpak/xdg-desktop-portal/pull/623/files
https://github.com/flatpak/xdg-desktop-portal/pull/628/files

**Comment by gostsdmitry** [comment]
@AsciiWolf
https://github.com/flatpak/xdg-desktop-portal-gtk/pull/351/files
;-)

**Comment by mwleeds** [comment]
@gostsdmitry thanks for your contribution! The commit history got a bit messy so I cleaned it up and make a new PR: #4548

**Comment by gostsdmitry** [comment]
@mwleeds Yes. Everything is OK.

**Pull request closed without merging**
