### PR TITLE
build-bundle: Add --from-commit option

### PR DESCRIPTION
**Pull request by TingPing**
This allows building smaller bundles that are deltas from a specific commit.

### CODE REVIEW

**Comment by mwleeds** [comment]
Then the bundle will only be useful to someone who already has that commit right?

**Comment by TingPing** [comment]
Correct. This is a fairly narrow use-case but it is useful for a tool @chergert and I are working on that transfers these over the network.

**Comment by alexlarsson** [comment]
Does installing these always work, even on older flatpak versions? If not we should bump the magic value (if commit is specified) to avoid confusing older flatpaks.

Also when installing when the base commit is not in the local repo, what error does this show? I think we want to add some manual checks there with a better error message when this fails.

**Comment by TingPing** [comment]
> Does installing these always work, even on older flatpak versions? 

I didn't test very old versions but it works totally fine on the current stable release.

> Also when installing when the base commit is not in the local repo, what error does this show?

`error: Commit 735a6d8af986208ad62b6907c0f71351927de40277ce7e4b0a32c5c247560d65, which is the delta source, is not in repository`

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
