### PR TITLE
coverage: Don't do parallell make check

### PR DESCRIPTION
**Pull request by alexlarsson**
This is running into some kind of timeout for me.

### CODE REVIEW

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Comment by matthiasclasen** [comment]
I think the timeout was me messing around with the test app, perhaps?

**Comment by alexlarsson** [comment]
I dunno, i tried to bump the timeouts, but it didn't help. Serial make check did though.

**Comment by alexlarsson** [comment]
Oh, i see, the regular "make check -j8" has a similar timeout error...

**Comment by alexlarsson** [comment]
Hmm, even the 1.0.3 release gets the timeout for me. I'm pretty sure that worked at some point.

**Pull request closed without merging**
