### PR TITLE
Enforce a more permissive umask

### PR DESCRIPTION
**Pull request by alexlarsson**
We enforce an umask of 022 (no world/group writable) in the cli and the system helper. This is necessary, because we need to create ostree repositories shared between the helper and the client, and a more strict umask breaks this.
    
It would be nice if we could just set this in a thread-local way when needed, but unfortunately umask() is not threadsafe or overridable in any local way.
    
This unfortunately means this it will not automatically work for libflatpak users...

### CODE REVIEW

**Comment by alexlarsson** [comment]
fixes https://github.com/flatpak/flatpak/issues/2829 and  https://github.com/flatpak/flatpak/issues/2114

**Comment by matthiasclasen** [comment]
Maybe this quirk is worth pointing out in the libflatpak doc somewhere?

"Use umask (022)"

**Comment by matthiasclasen** [comment]
Looks good, otherwise

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Comment by kalev** [comment]
Does it make sense to do the same in gnome-software main(), https://gitlab.gnome.org/GNOME/gnome-software/merge_requests/201 ?

**Pull request closed without merging**
