### PR TITLE
Update Czech translation

### PR DESCRIPTION
**Pull request by AsciiWolf**

### CODE REVIEW

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r+

**Comment by AsciiWolf** [comment]
@matthiasclasen I see that the commit was only approved and not actually merged. :)

**Comment by matthiasclasen** [comment]
it was merged to 1.0.x. was that not your intention ?

**Comment by AsciiWolf** [comment]
It was. :-) I just was confused because this PR was not closed.

**Pull request closed without merging**
