### PR TITLE
Don't enable debug output from fuse

### PR DESCRIPTION
**Pull request by alexlarsson**
Fixes https://github.com/alexlarsson/xdg-document-portal/issues/29

### CODE REVIEW

**Comment by alexlarsson** [comment]
Oh, they are parsed internally in libfuse.

**Comment by alexlarsson** [comment]
https://github.com/libfuse/libfuse/blob/fuse-2_9_bugfix/lib/fuse_lowlevel.c#L2475

**Comment by pwithnall** [comment]
I guess you might want to conditionally hook this up to some verbose argument to `xdp-fuse.c` at some point (maybe `G_MESSAGES_DEBUG`?), but this looks fine to me for now.

**Comment by pwithnall** [comment]
@rh-atomic-bot r+ ac0cc69fa698f43f17655ea177ce6fb1df3bb406

**Comment by pwithnall** [comment]
Booo :'-(

**Comment by alexlarsson** [comment]
@pwithnall Added you, accept and try again

**Comment by pwithnall** [comment]
@rh-atomic-bot r+ ac0cc69

**Pull request closed without merging**
