### PR TITLE
Fix flatpak enter being multi-threaded and failing

### LINKED ISSUE #3646: flatpak enter can fail because its process is multithreaded
## Linux distribution and version
Fedora silverblue 32
## Flatpak version
1.6.3 and master
## Description of the problem
flatpak enter fails with `error: Can't enter user_base namespace: Invalid argument`. It might be the root cause of issues #3406 and #3059
## Steps to reproduce
```bash
flatpak run SOME_ID
flatpak enter INSTANCE bash
```
or with the child PID.

## Cause of the problem

We are hitting the following error condition of `setns`:
```
EINVAL The caller is multithreaded and tried to join a new user namespace.
```

This can be seen by running `flatpak enter` with:
```bash
G_MESSAGES_DEBUG=all ./flatpak -vvv enter 47860 bash
```
which prints the following warning:
```
GLib-DEBUG: 14:11:17.858: unsetenv() is not thread-safe and should not be used after threads are created
```
and which I double checked by adding a sleep in flatpak and remarking that the process contains three threads, named `flatpak, gmain, gdbus`.

I also noted that if I comment out [the line](https://github.com/flatpak/flatpak/blob/master/app/flatpak-main.c#L874)
```C
g_vfs_get_default ();
```
in `main`, the problem disappears. I think, but I have not checked, that this is cause by [this loop](https://github.com/GNOME/glib/blob/a8263add4538e0c15c8115710a2010793fae1421/gio/giomodule.c#L1383-L1384) in glib. Maybe some modules spawn threads when they are used/initialized?

I believe that the list of modules depends on the environment variables, which explains that the problem does not always appear (on my machine, it works with `sudo` but not `sudo -E` for example). 

I think the solution is to guard the GVfs dance after [this ckeck](https://github.com/flatpak/flatpak/blob/ff677cfdbc592c235a291638b02ac77b4ca942bd/app/flatpak-main.c#L761-L766). I would be happy to do a pull request if this sounds like a good idea.

### PR DESCRIPTION
**Pull request by ineol**
flatpak enter must not be multi-threaded because it calls setns. This was causing a problem because g_vfs_get_default spawns threads in some environments.

I don't understand well enough the reason for the gvfs workaround to be sure that this does not cause other problems.

Fixes #3646 

Might be relevant to #3406 and #3059.

### CODE REVIEW

**Comment by alexlarsson** [comment]
Its a bit funny that the code that tries to enforce using only the local gvfs backend is causing problems. Without this code it will load and use the full dbus-based, complicated gvfs backend the first time we create a GFile. It might be that flatpak enter doesn't use a GFile though, so it is accidentally safe...

**Comment by alexlarsson** [comment]
Yeah, looks like it manages to not hit GFile, so i guess we're ok with this.

**Comment by ineol** [comment]
@alexlarsson 
> Its a bit funny that the code that tries to enforce using only the local gvfs backend is causing problems. Without this code it will load and use the full dbus-based, complicated gvfs backend the first time we create a GFile.

So I investigated a bit. `g_vfs_get_default` ends up calling `giomodule.c:g_io_modules_scan_all_in_directory_with_scope` at path `GIO_MODULE_DIR` or `/usr/lib64/gio/modules`. If the cache file has been _modified_ before the last _status change_ of the extension file, it loads and unloads the extension.

The problem, in the case of Silverblue/ostree, is that the modified time of every file is epoch 0, but the status change time is the time of update (I think), and so we load every GIO module unconditionnaly! I suppose this should be fixed upstream, maybe by looking at the status change of the cache file as well?

Setting `GIO_MODULE_DIR` to an empty or an non-existing directory or a file fixes the problem as well. So maybe it is better to also set-unset this environment variable when calling `g_vfs_get_default`?

**Comment by alexlarsson** [comment]
@ineol Yeah, that sounds like something worth brining up upstream, because it will affect performance in general on silverblue.

**Pull request merged**
