### PR TITLE
run: Print errno error code consistently.

### PR DESCRIPTION
**Pull request by sebras**
Commit 352e761c0ef506f42f818c1da39ae504d45fea36 started the trend
to print the errno error code when unable to open a file, make all
occurrences where files are opened print the same kind of message.

### CODE REVIEW

**Comment by sebras** [comment]
I discovered this while translating the package to Swedish.

**Comment by sebras** [comment]
I found a typo in an unrelated file just now. Let's fix both! :)

**Comment by TingPing** [comment]
Should probably use `g_strerror()`. UTF-8 encoding, thread-safe, more portable, etc.

**Comment by sebras** [comment]
Ok, in that case I want to do a first commit changing all of the strerror() uses to g_strerror() and then apply my corrected patch. Give me a minute.

**Comment by sebras** [comment]
Done. I tagged on the translation for Swedish here. if that's the wrong thing to do let me know. I'm not sure how PRs really work...

**Pull request merged**
