### PR TITLE
Uninstall all

### PR DESCRIPTION
**Pull request by matthiasclasen**
Somewhat experimental.

This adds two ways to select multiple of the offered refs for uninstalling.

- By adding an "All of the above" choice
- By accepting input of the form: 1-5,10 13

### CODE REVIEW

**Comment by alexlarsson** [comment]
This doesn't seem to handle duplicates very well.  Especially when you use a range which includes the all of the above one.

**Comment by alexlarsson** [comment]
Otherwise it looks good.

**Comment by matthiasclasen** [comment]
Fixed up to avoid duplicates

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r=alexlarsson

**Pull request closed without merging**
