### PR TITLE
po: Update POTFILES.in for usb

### PR DESCRIPTION
**Pull request by hfiguiere**
See https://github.com/flatpak/flatpak/pull/5620#issuecomment-2426460452

### CODE REVIEW

**Comment by swick** [comment]
@piotrdrag

**Comment by piotrdrag** [comment]
So am I to understand that an end user will be presented with e.g. `USB query rule 'vnd' must have a valid 4-digit hexadecimal vendor id` or `USB query rule 'cls' must be in the form CLASS:SUBCLASS or CLASS:*` at some point while using Flatpak interfaces? What are they supposed to do with that information?

**Comment by hfiguiere** [comment]
It's part of the command line interface. Localisation is supposed to present these in the user language.

**Comment by piotrdrag** [comment]
As far as I can tell, no other `g_set_error`s are marked for translation across Flatpak’s codebase.

**Comment by hfiguiere** [comment]
There are actually a few that are translatable prior to this.

**Pull request merged**
