### PR TITLE
Fix some error code paths on flatpak_dir_deploy

### PR DESCRIPTION
**Pull request by mwleeds**

### CODE REVIEW

**Comment by mwleeds** [comment]
The CI failure is due to an issue with cloning malcontent, and gitlab.freedesktop.org has the status message "There is an ongoing issue causing HTTP clones of some repositories to time out. If this is affecting you, please try cloning via SSH instead. This is currently being investigated and hoped to be resolved 29th Dec."

**Comment by smcv** [comment]
LGTM

**Review by smcv — APPROVED** [review]

**Comment by smcv** [comment]
Do we also want this in 1.12.x? I have not included it in #4646.

**Comment by mwleeds** [comment]
> Do we also want this in 1.12.x? I have not included it in #4646.

Yeah, seems appropriate to backport

**Pull request merged**
