### PR TITLE
document-portal: Handle bubblewrap changing to drop /newroot

### PR DESCRIPTION
**Pull request by cgwalters**
There's an oustanding bubblewrap PR where we'd like to change how
we set up the rootfs; a side effect of this will be that /newroot
disappears from the `/proc` links:
[bubblewrap pull 172](https://github.com/projectatomic/bubblewrap/pull/172).

I took a stab here at adapting the code to work in both the old and new cases.
Just compile tested at the moment. There's a lot of subtleties in this code; in
particular how we end up mutating-in-place the path buffer and how that
interacts with inspecting it.

### CODE REVIEW

**Comment by cgwalters** [comment]
@alexlarsson is this on the right track?

**Comment by alexlarsson** [comment]
Looks good to me.
@rh-atomic-bot r+

**Comment by alexlarsson** [comment]
I tested this by building and installing https://github.com/flatpak/freedesktop-sdk-base/blob/1.6/org.freedesktop.Builder.json

Then:
```
$ flatpak run --nofilesystem=host org.freedesktop.Builder 
bash-4.3$ flatpak document-export /app/manifest.json 
/run/user/1000/doc/dba7dba2/manifest.json
```
Which i could cat from outside the sandbox.

This only tests that we didn't regress in the /newroot/ codepath though.

**Comment by cgwalters** [comment]
Lifting WIP then.

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Comment by alexlarsson** [comment]
@cgwalters Note, there is some /newroot code in xdg-desktop-portal too

**Comment by cgwalters** [comment]
Where is `org.freedesktop.Builder`?

**Pull request closed without merging**
