### PR TITLE
Support multiple nvidia cards

### PR DESCRIPTION
**Pull request by TingPing**
This was reported here: https://github.com/flathub/org.freedesktop.Platform.GL.nvidia/issues/7

### CODE REVIEW

**Comment by TingPing** [comment]
Also this is probably worth backporting to the stable series.

**Comment by leinardi** [comment]
Hey guys, is there an ETA for this to be released?

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Comment by alexlarsson** [comment]
Cherrypicked it to the flatpak-1.2.x branch

**Pull request closed without merging**
