### PR TITLE
Update Czech translation [flatpak-1.6.x]

### PR DESCRIPTION
**Pull request by AsciiWolf**
Just a small fix.

### CODE REVIEW

**Comment by mwleeds** [comment]
bot, test pull request

**Comment by mwleeds** [comment]
I thought @rh-atomic-bot would be out of the picture now that we're using GitHub actions. I guess not?

**Comment by AsciiWolf** [comment]
It seems that this PR was still not merged.

**Comment by mwleeds** [comment]
Right, I think I don't have the right level of permissions

**Comment by AsciiWolf** [comment]
I think it is an issue with the rh-atomic-bot itself having problems when merging PRs to a non-master branches.

**Comment by AsciiWolf** [comment]
@alexlarsson @matthiasclasen Could you guys please merge this small fix? It is already in master. Thanks! :-)

**Comment by AsciiWolf** [comment]
bot, test pull request

**Pull request merged**
