### PR TITLE
Set up selinux for sandboxes

### PR DESCRIPTION
**Pull request by matthiasclasen**
This could be useful, e.g. for restricting what apps can access in the kernel keyring (which is otherwise wide open).

### CODE REVIEW

**Comment by matthiasclasen** [comment]
Here's a quick implementation. It makes the flatpak-session-helper do the same mcs label management as docker-daemon. Sadly, this does not currently work, since the policy does not allow the right transitions. The error I get is:

"SELINUX_ERR op=security_bounded_transition seresult=denied oldcontext=unconfined_u:unconfined_r:unconfined_t:s0-s0:c0.c1023 newcontext=system_u:system_r:svirt_lxc_net_t:s0:c51,c817"

**Comment by matthiasclasen** [comment]
From a quick review with Dan:

- need to label container content at install time. For now, we can use user_home_t, eventually, we should use a label that prevents writing from the sandboxed application

- need to use the current user and role when creating the sandboxed labels (ie, we need to use
  unconfined_u:unconfined_r:svirt_lxc_net_t:s0:c51,c817)

- should use the same unique mcs label for the app as long as it is installed. One idea for that is to take it from the label that was used at install time

- should ideally ensure system-wide uniqueness of mcs labels

**Comment by matthiasclasen** [comment]
We are discussion necessary policy changes in https://github.com/fedora-selinux/selinux-policy/issues/142

**Comment by alexlarsson** [comment]
Closing this for now.

**Pull request closed without merging**
