### PR TITLE
Don't prompt twice for flatpak uninstall --unused

### PR DESCRIPTION
**Pull request by uajain**
https://github.com/flatpak/flatpak/issues/1928

### CODE REVIEW

**Comment by alexlarsson** [comment]
This seems like a weird change. Why are you setting opt_yes, that should only be set if the user passed -y to flatpak and will disable all following questions. Seems like a hack rather than a fix.

**Comment by uajain** [comment]
Yes, it was a hack. Made an second attempt to address the issue. It may still look like a hack :-P

**Comment by alexlarsson** [comment]
That is also wrong. Disabling interaction is a generic option that modifies *all* interactions, not just this particular one. Its never right to set it unless the user explicitly asked for it.

**Comment by alexlarsson** [comment]
Better fix in https://github.com/flatpak/flatpak/pull/2056

**Pull request closed without merging**
