### PR TITLE
Updated Swedish Translation

### PR DESCRIPTION
**Pull request by hanklank**
Again, an update to the Swedish Translation.

### CODE REVIEW

**Comment by haaninjo** [comment]
@hanklank I have reviewed at the translation and attached it on https://l10n.gnome.org/vertimus/flatpak/master/po/sv after some minor changes.

**Comment by hanklank** [comment]
@haaninjo Thanks, I have updated the PR with your suggestions.

**Comment by mwleeds** [comment]
@hanklank could you squash those commits together? Basically just run `git rebase -i HEAD^^` and change the newer one from `pick` to `fixup` then exit the editor. Then you'll have to `git push -f origin master` (assuming `origin` is your fork).

**Comment by hanklank** [comment]
git rebase -i HEAD^^ just said successfully rebased and it didn't open up the editor for me  @mwleeds. Maybe you could do an squash-and-merge as described in https://help.github.com/articles/merging-a-pull-request/, as i'm not that good with git anyway besides the basics.

**Pull request merged**
