### PR TITLE
pt_BR translations file

### PR DESCRIPTION
**Pull request by frnogueira**
12% to test!

### CODE REVIEW

**Comment by frnogueira** [comment]
bot, test pull request

**Comment by alexlarsson** [comment]
bot, add author to whitelist

**Comment by piotrdrag** [comment]
This PR adds files that shouldn't be in git: po/messages.po and po/pt_BR.mo.

**Comment by alexlarsson** [comment]
@piotrdrag Ah, missed that. Fixed in master.

**Pull request merged**
