### PR TITLE
Update es.po

### PR DESCRIPTION
**Pull request by Rodhos**
Update spanish translation.

### CODE REVIEW

**Comment by smcv** [comment]
Please could you use `git rebase` to turn this PR into a single commit with your changes?

**Comment by smcv** [comment]
#5052, #5059, #5126 are some good examples of what a translation update should ideally look like.

**Comment by Rodhos** [comment]
@smcv I'm trying to rebase. Not sure if I managed to do it properly.  I'm not experienced with git.
Thanks for telling me about this command. I will try my best.

**Comment by Rodhos** [comment]
Why 11 files changed? what happened?

**Comment by smcv** [comment]
I don't know what you've done here. It might be easier to close this PR, and open a new one with the `es.po` that you want.

**Pull request closed without merging**
