### PR TITLE
Russian translation update

### PR DESCRIPTION
**Pull request by gostsdmitry**

### CODE REVIEW

**Comment by smcv** [comment]
Please could you use `git rebase` to turn this into a single commit with your changes, instead of multiple commits that delete and re-create the Russian translation?

**Comment by smcv** [comment]
#5052, #5059, #5126 are some good examples of what a translation update should ideally look like.

**Comment by gostsdmitry** [comment]
> Please could you use `git rebase` to turn this into a single commit with your changes, instead of multiple commits that delete and re-create the Russian translation?

I'm sorry. I work directly on the GitHub site without utilities on the computer and the command line.

**Comment by gostsdmitry** [comment]
[smcv](https://github.com/smcv)  #5312

**Pull request closed without merging**
