### PR TITLE
update Indonesian translation

### PR DESCRIPTION
**Pull request by cho2**
update Indonesian translation

### CODE REVIEW

**Comment by mwleeds** [comment]
Thanks!
@rh-atomic-bot r+ 2511f9f

**Comment by mwleeds** [comment]
bot, retest this please

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+ 2511f9f

**Comment by alexlarsson** [comment]
bot, retry

**Comment by alexlarsson** [comment]
retry

**Pull request merged**
