### PR TITLE
Add completion for --installation=

### PR DESCRIPTION
**Pull request by matthiasclasen**
Complete all the things.

### CODE REVIEW

**Comment by aiamuzz** [comment]
you mean we can hit tab to fill the custom installation name ?

**Comment by matthiasclasen** [comment]
That is what this PR does, yes.

**Comment by aiamuzz** [comment]
splendid ... i was meaning to request it as a feature but held back thinking it may be struck down as there may be only one name ... but typing that name each time was cumbersome though ... glad you have picked it up !

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r+

**Pull request merged**
