### PR TITLE
flatpak-utils-http: Don’t use GMainLoop

### PR DESCRIPTION
**Pull request by pwithnall**
Iterate the `GMainContext` manually instead. This makes the exit
condition from the loop much more obvious, and eliminates the potential
class of problems where `g_main_loop_quit()` is called before
`g_main_loop_run()` and has no effect.

Signed-off-by: Philip Withnall <pwithnall@endlessos.org>

### CODE REVIEW

**Comment by pwithnall** [comment]
Not tested. Proposing it because it might help @aleixpol with some flatpak threading issues — hopefully @aleixpol can say if it helps (and therefore works). :slightly_smiling_face:

**Comment by aleixpol** [comment]
Hi, sorry for not replying earlier.

I did test that branch and it didn't seem to address my issue (which is that when multiple requests to the same url get issued at the same time in parallel, it gets confused and some of them never finish).

Maybe I haven't fully grasped libflatpak threading concept and I need to lock on some resources before accessing in parallel?

**Comment by pwithnall** [comment]
So this branch behaved the same as the normal flatpak? If so, that’s not a bad indication.

Grab me on IRC again if you want to debug further; this branch should make it a bit easier to debug since the download thread which isn’t terminating will now be iterating below the new `g_main_context_iteration()` loop in a context where its exit conditions are accessible to be inspected with `gdb`.

**Review by smcv — APPROVED** [review]
Not really a maintainer, but this looks like good refactoring to me.

**Comment by smcv** [comment]
> Not really a maintainer

Now I am! Merging.

**Comment by alexlarsson** [comment]
So, this merge seems to be the reason all the CI tests hang in the tests/test-oci-registry@system.wrap test currently.  What happens is that flatpak calls the system-helper to update the OCI summary, the system-helper tries to download the oci index, but that hangs forever inside flatpak_cache_http_uri_once.

**Comment by pwithnall** [comment]
Feel free to revert; I won’t have time to look at this any time soon.

**Pull request merged**
