### PR TITLE
builder: add cmake-ninja support

### PR DESCRIPTION
**Pull request by Barthalion**
Please don't yell too much at me, I didn't touch C in ages. Note that for some reason it currently doesn't work as expected, CMake returns `CMake Error: Could not create named generator 'Ninja'` or `CMake Error: Could not create named generator 'Unix Makefiles'`. I looked at debug log and ran exactly the same command:

```flatpak build --nofilesystem=host --filesystem=/home/bp/dev/flatpak-ppsspp/.flatpak-builder/build/ppsspp-12 --bind-mount=/run/build/ppsspp=/home/bp/dev/flatpak-ppsspp/.flatpak-builder/build/ppsspp-12 --build-dir=/run/build/ppsspp --bind-mount=/run/ccache=/home/bp/dev/flatpak-ppsspp/.flatpak-builder/ccache --env=PATH=/run/ccache/bin:/app/bin:/usr/bin --env=CCACHE_DIR=/run/ccache /home/bp/dev/flatpak-ppsspp/builddir cmake -DCMAKE_INSTALL_PREFIX:PATH='/app' -G'Unix Makefiles' .```

…which works just fine. I would appreciate some help with that.

### CODE REVIEW

**Comment by TingPing** [comment]
My guess is that `-G'Unix Makefiles'` is two arguments, so shoving them in one arg is the problem.

**Comment by Barthalion** [comment]
Good catch. I will rework the patch a little bit so `build` uses arguments from another array instead of passing each variable explicitly.

**Comment by Barthalion** [comment]
So despite `-G` and `'Ninja'` being passed as separate arguments, it fails with the same error.

**Comment by TingPing** [comment]
Remove the extra `'`s too.

**Comment by Barthalion** [comment]
That was it. Thanks @TingPing.

**Comment by alexlarsson** [comment]
bot, add author to whitelist

**Comment by alexlarsson** [comment]
bot, test pull request

**Pull request merged**
