### PR TITLE
Handle empty remote URLs better

### PR DESCRIPTION
**Pull request by mwleeds**

### CODE REVIEW

**Comment by alexlarsson** [comment]
I'm not sure giving this error in this case is right, because we're using empty urls to mean "disabled". We should probably say that is is disabled instead.

**Comment by mwleeds** [comment]
@alexlarsson Is that a backwards compatibility thing? It looks like `remote-modify --disable` sets `xa.disable=true`.

**Comment by alexlarsson** [comment]
Yeah, that was added later. See e.g. flatpak_dir_get_remote_disabled()

**Comment by mwleeds** [comment]
@alexlarsson I changed the error message and force-pushed so I could change the commit message also

**Comment by mwleeds** [comment]
Maybe `G_IO_ERORR_INVALID_DATA` isn't the best error for this; I'm not sure

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
