### PR TITLE
transaction: Fix gtk-doc warning

### PR DESCRIPTION
**Pull request by mwleeds**

### CODE REVIEW

**Comment by matthiasclasen** [comment]
I couldn't figure this out: Why does gtk-doc have opinions about how I name my parameters?

Usually it only acts up when there's a mismatch between header, source and doc comment. But there isn't one, here.

**Comment by matthiasclasen** [comment]
And there's a bunch of other api where @self is not an issue at all...

**Comment by mwleeds** [comment]
I guess because the vfunc uses "transaction": https://github.com/flatpak/flatpak/blob/master/common/flatpak-transaction.h#L125

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
