### PR TITLE
Update Czech translation

### PR DESCRIPTION
**Pull request by AsciiWolf**
Add new strings.

### CODE REVIEW

**Comment by mwleeds** [comment]
@rh-atomic-bot retry

**Comment by mwleeds** [comment]
@cgwalters do you know if the bot is ignoring me?

**Comment by AsciiWolf** [comment]
@rh-atomic-bot retry

**Comment by cgwalters** [comment]
@mwleeds Had to reprovision the bot up again (status is https://homu-projectatomic-ci-infra.e8ca.engint.openshiftapps.com/ )

**Comment by cgwalters** [comment]
Unfortunately though the bot is ignoring `retry` here as...well it's confusing, that command only applies *after* a PR has been approved.

**Comment by cgwalters** [comment]
bot, retest this please

**Comment by mwleeds** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
