### PR TITLE
Update appstream data when searching

### PR DESCRIPTION
**Pull request by mwleeds**
We may want to add an `--offline` option to search the appstream data that's already downloaded, but that can be a separate issue.

### CODE REVIEW

**Comment by TingPing** [comment]
I don't think we should update every single search, I think it should behave like `dnf` where it considered it outdated after the last update is a day old or such.

**Comment by mwleeds** [comment]
I tried to add the expiration feature @TingPing mentioned but it doesn't seem to be working correctly, so this isn't ready to be merged.

**Comment by mwleeds** [comment]
It turns out that it was (correctly) not updating appstream data when it was already on the latest commit, so this is ready for review.

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
