### PR TITLE
[1.14.x] Backport various bug fixes from main

### PR DESCRIPTION
**Pull request by smcv**

### CODE REVIEW

**Comment by smcv** [comment]
Please could another maintainer take responsibility for testing and releasing 1.14.6, with more or fewer backports as desired? I'd prefer not to have the whole community relying on me to be Flatpak's de facto release manager - I'm a single point of failure for too many projects, and the result is that we only rarely get releases.

**Comment by GeorgesStavracas** [comment]
I see that you updated the NEWS file to 1.14.7 already, fantastic. The backports look good to me, but I want to test it. I think I can help put this release out next week.

**Comment by GeorgesStavracas** [comment]
Thanks for preparing this Simon

**Comment by smcv** [comment]
> I think I can help put this release out next week

Next week is probably good timing for it: a long enough wait to know whether 1.14.6 caused any important regressions (and if it did, hotfix those instead of doing an ordinary stable release), but soon enough to get the rest of these bug fixes out to users in a reasonably timely way.

**Comment by GeorgesStavracas** [comment]
Thanks for merging this. Since no critical regression has been reported from the CVE fix, I'll set aside some time to roll a release this Friday.

**Pull request merged**
