### PR TITLE
pulseaudio: Respect pulseaudio env vars and config file

### PR DESCRIPTION
**Pull request by alexlarsson**
Instead of just assuming the default pulseaudio socket we look
at the same environment and config files that pulseaudio does.

This does not currently look at the X11 properties.

This is a cleaned up and rebased version of https://github.com/flatpak/flatpak/pull/1208

### CODE REVIEW

**Comment by vbatts** [comment]
@alexlarsson 
```shell
[vbatts@noyee] {master *} ~$ /usr/local/bin/flatpak run org.supertuxproject.SuperTux
ALSA lib pulse.c:243:(pulse_connect) PulseAudio: Unable to connect: Connection refused

AL lib: (EE) ALCplaybackAlsa_open: Could not open playback device 'default': Connection refused
[WARNING] /run/build/supertux/src/audio/sound_manager.cpp:67 Couldn't initialize audio device: Couldn't open audio device.
[vbatts@noyee] {master *} ~$ xprop  -root | grep -i ^PULSE_SERVER
PULSE_SERVER(STRING) = "{83d055f52df9ea80f9550b4259f08ebf}unix:/tmp/pulse-PKdhtXMmr18n/native"
[vbatts@noyee] {master *} ~$ export PULSE_SERVER="{83d055f52df9ea80f9550b4259f08ebf}unix:/tmp/pulse-PKdhtXMmr18n/native"
[vbatts@noyee] {master *} ~$ /usr/local/bin/flatpak run org.supertuxproject.SuperTux
```

It only works when PULSE_SERVER is set, but that is same as #1208 achieved

**Comment by alexlarsson** [comment]
Yeah, we should probably have a xprop shell-out fallback.
But... shudder...

**Comment by alexlarsson** [comment]
@rh-atomic-bot r+

**Comment by alexlarsson** [comment]
I think shelling out is doable:
```
$ xprop -root -notype PULSE_SERVER 
PULSE_SERVER = "{f7f828058a8a43c2877000a279c88529}unix:/run/user/1000/pulse/native"
```

**Comment by alexlarsson** [comment]
Wanna look at it?

**Comment by vbatts** [comment]
i'm seeing it (your comment) on my screen right now!

**Comment by vbatts** [comment]
if something nasty like shelling out and cleaning up the output is need (allowed), then I'm not entirely comfortable being the one responsible for writing that...

**Pull request closed without merging**
