### PR TITLE
uninstall: Add a --remove-data option

### PR DESCRIPTION
**Pull request by matthiasclasen**
When --cleanup is passed, remove all 'unowned' app data directories in ~/.var/app/.

I would be happier if this could be a library api, so it would be available to gnome-software as well.
But I haven't come up with a good place to fit it yet: flatpak_transaction_set_cleanup_app_dirs() ?

### CODE REVIEW

**Comment by TingPing** [comment]
Some thoughts:

- Shouldn't this be an option when removing an application? `flatpak uninstall --cleanup org.example.App`
- If there is a command to clean up all left over directories it should probably be much more explicit and prompt on each one
- Maybe the data should be moved to the trash to be less accidentally destructive
- Bikeshedding, but `cleanup` doesn't convey that it is deleting user data very much to me

**Comment by matthiasclasen** [comment]
Changed it to --remove-data, and made it remove permissions as well.

**Comment by TingPing** [comment]
`--remove-data` is good.

> made it remove permissions as well.

Hmm, I wonder if that shouldn't be removed on every uninstall? I'm just wondering if users would expect that a permission they added to an application a year ago and removed still applies silently.

**Comment by matthiasclasen** [comment]
> Hmm, I wonder if that shouldn't be removed on every uninstall? I'm just wondering if users would expect that a permission they added to an application a year ago and removed still applies silently on a fresh install.

For now, I'll keep this under the --delete-data option

**Comment by matthiasclasen** [comment]
@rh-atomic-bot r+

**Pull request closed without merging**
